### ISSUE TITLE
Lack of Python3 in many of these DGA scripts

### ISSUE THREAD

**Issue by teward** [baderj/domain_generation_algorithms#15]
(I am merely the messenger here)

It was observed many of the DGA mechanisms here are *not* in Python 3, suggesting that either they are no longer supported or no longer relevant.  Is this the case?  And if so, should those Py2 algos be ignored for modern information gathering?

Alternatively, if someone did a Python3 port of those functions would you consider reviewing that as a pull/merge request?

**Comment by baderj** [comment]
I'm not sure I understand. All the algorithms run with Python 3, including the latest Python 3.11. Do you have a concrete example of a script that would need to be migrated? Would that be because the algorithm does not run in your environment, or because the latest Python versions offer a more concise way to write the algorithm?

The purpose of this repo is mostly to document the DGAs in an easy to understand manner and to provide algorithms for research, e.g., to generate test data to test detection algorithms. 

- The repo is not meant as a comprehensive collection of DGA. It only contains the ones that I personally reverse engineered. To get an near complete archive, check out the [DGArchive](https://dgarchive.caad.fkie.fraunhofer.de)
- The repo is not meant to provide any data for IDS, incident response or threat hunting. Use the feed from DGArchive for a list of current DGA domains, or one of the many feeds that filter the list down to only active domains

**Comment by teward** [comment]
So as I said i'm not the source of the message, just the messenger.  But according to those I work with (we have an MCT - malware and cyber threats - team that runs the DGA algos through a resolver script to generate DGA data (domains -> ip and GeoIP on the IPs, etc.) into a data feed for multiple partners who *do* have that for data)) some of these don't run in Python 3.

I'll sync up with the internal team and get back to you on specifics if need be, but thanks for your reply.

**Comment by ynadji** [comment]
FWIW, I made a PR and got it merged (#5) that fixed exactly this issue when I ran into it. I'm curious if the team is using an older version or if some newly added ones need 2? This will at least tell you @baderj is happy to merge a fix like this and a specific example would be helpful.
